project:
  type: website
  output-dir: docs

website:
  title: "Swapnaja Kulkarni"
  navbar:
    left:
      - href: index.qmd
      - about.qmd
      - Projects.qmd
      - dummy1.qmd
      - dummy2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true